LOAD DATA INFILE 'Datas/boisson.csv' INTO TABLE boisson FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'IGNORE 1 ROWS;
LOAD DATA INFILE 'Datas/focaccia.csv' INTO TABLE focaccia FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'IGNORE 1 ROWS;
LOAD DATA INFILE 'Datas/ingredient.csv' INTO TABLE ingredient FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'IGNORE 1 ROWS;
LOAD DATA INFILE 'Datas/marque.csv' INTO TABLE marque FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'IGNORE 1 ROWS;
